#ifndef LWESP_OPTS_HDR_H
#define LWESP_OPTS_HDR_H

#define LWESP_CFG_OS 1
#define LWESP_CFG_INPUT_USE_PROCESS 1
#define LWESP_CFG_MEM_CUSTOM 0
#define LWESP_MEM_SIZE 0x4000
#define LWESP_CFG_NETCONN 1
#define LWESP_CFG_NETCONN_RECEIVE_TIMEOUT 1
#define LWESP_CFG_AT_PORT_BAUDRATE 115200

#endif /* LWESP_OPTS_HDR_H */
